modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"
issueTrackerURL="https://github.com/bh679/enderchestpersistence-mc/issues"

[[mods]]
modId="enderchestpersistence"
version="${version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
displayURL="https://github.com/bh679/enderchestpersistence-mc"

[[dependencies.enderchestpersistence]]
    modId="neoforge"
    type="required"
    versionRange="[${neoforge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.enderchestpersistence]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
